title: iPod Puppy Blog
description: A cozy feed of updates
baseurl: ""  # Leave blank unless deploying to a subfolder
url: "https://yourusername.github.io"  # Replace with your actual GitHub Pages URL

collections:
  comics:
    output: true
    permalink: /comics/:title/

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  collection: comics
  per_page: 5  # Number of comics per page
  permalink: /comics/page:num/
