title: iPod Puppy Blog
description: A cozy feed of updates
baseurl: ""  # Leave blank unless deploying to a subfolder
url: "https://yourusername.github.io"  # Replace with your actual GitHub Pages URL

collections:
  comics:
    output: true
    permalink: /comics/:title/
  guestbook:
    output: true
    permalink: /guestbook/:title/

# Removed jekyll-paginate-v2 because it's not supported on GitHub Pages
# pagination:
#   enabled: true
#   collection: comics
#   per_page: 5
#   permalink: /comics/page:num/
